excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

disabled_rules:
  - trailing_whitespace

identifier_name:
  max_length:
    warning: 45
    error: 60   
  min_length:
    warning: 1

line_length: 
    warning: 250
    ignores_comments: true